### ISSUE TITLE
Error encoding en pag. 179

### ISSUE THREAD

**Issue by jvruoc** [jvruoc/rent_prices#29]
New page:
app         | DEBUG    [scraper.py:139] https://www.fotocasa.es/es/alquiler/viviendas/madrid-capital/todas-las-zonas/l/179
app         | INFO     [scraper.py:198] Retardo (10 s.) -> descarga de link: https://www.fotocasa.es/es/alquiler/viviendas/madrid-capital/todas-las-zonas/l/179
app         | INFO     [scraper.py:117] Page loaded
app         | INFO     [scraperFotocasa.py:75] Finished scroll
app         | INFO     [scraperFotocasa.py:42] Cantidad de inmuebles en la página: 30
app         | INFO     [main.py:42] Grabando elemento id: fc-162031982
app         | DEBUG    [database.py:118] Actualizado el inmueble fc-162031982 con el precio 1295
app         | INFO     [main.py:42] Grabando elemento id: fc-162031059
app         | DEBUG    [database.py:118] Actualizado el inmueble fc-162031059 con el precio 999
app         | INFO     [main.py:42] Grabando elemento id: fc-162028057
app         | DEBUG    [database.py:118] Actualizado el inmueble fc-162028057 con el precio 3500
app         | INFO     [main.py:42] Grabando elemento id: fc-162026999
app         | Traceback (most recent call last):
app         |   File "//src/rent_prices/main.py", line 73, in <module>
app         |     main()
app         |   File "//src/rent_prices/main.py", line 44, in main
app         |     Db.insert_or_update_price('rents', item['_id'], item)
app         |   File "/src/rent_prices/utilities/database.py", line 102, in insert_or_update_price
app         |     Db.insert(collection,new_data)
app         |   File "/src/rent_prices/utilities/database.py", line 42, in insert
app         |     Db.DB[collection].insert_one(data)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 542, in insert_one
app         |     self._insert_one(
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 494, in _insert_one
app         |     self.__database.client._retryable_write(acknowledged, _insert_command, session)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1386, in _retryable_write
app         |     return self._retry_with_session(retryable, func, s, None)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1274, in _retry_with_session
app         |     return self._retry_internal(retryable, func, session, bulk)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1307, in _retry_internal
app         |     return func(session, sock_info, retryable)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 481, in _insert_command
app         |     result = sock_info.command(
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/pool.py", line 771, in command
app         |     self._raise_connection_failure(error)
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/pool.py", line 742, in command
app         |     return command(
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/network.py", line 128, in command
app         |     request_id, msg, size, max_doc_size = message._op_msg(
app         |   File "/usr/local/lib/python3.9/site-packages/pymongo/message.py", line 673, in _op_msg
app         |     return _op_msg_uncompressed(flags, command, identifier, docs, check_keys, opts)
app         | UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1870-1871: surrogates not allowed

**Comment by jvruoc** [comment]
En el conenido de la descripción de este inmueble 'fc-162026999' vienen unos caracteres que generan error al hacer el encode a  utf-8

```
>>> data = u'\ud83d\ude0a'
>>> result = data.encode('utf-8', 'surrogatepass')
>>> result.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
>>> data = r'\ud83d\ude0a'
>>> result = data.encode('utf-8', 'surrogatepass')
>>> result.decode('utf-8')
'\\ud83d\\ude0a'
```

**Comment by jvruoc** [comment]
Se tienen que eliminar caracteres utf-8 inválidos. Se hace con encode('utf-8', errors='replace').decode('utf-8')
